# Docker-compose override examples
# ================================
#
# Make a copy of this file and name it `docker-compose.override.yml`, then
# choose one among the following configurations and uncomment the lines.
# Finally cross your fingers and run `INITIAL=1 docker-compose up`.

# MINIMAL CONFIGURATION
# ~~~~~~~~~~~~~~~~~~~~~
#
# Visit http://localhost:8000/ to access the Django dev server and
# http://localhost:3000/ to access the Webpack dev server.
#
# Visit http://localhost:8025 to access the project's fake mail box.
#
# version: '3.8'
# services:
#   backend:
#     ports:
#       - 127.0.0.1:8000:8000
#   frontend:
#     ports:
#       - 127.0.0.1:3000:3000
#   mailhog:
#     ports:
#       - 127.0.0.1:8025:8025

# PONTSUN CONFIGURATION
# ~~~~~~~~~~~~~~~~~~~~~
#
# Set up pontsun (https://github.com/liip/pontsun) and start it. Then visit
# https://pyorc.docker.test/ to access the Webpack dev server.
#
# Visit https://pyorc-mail.docker.test/ to access the project's fake mail box.
#
#version: '3.4'
#x-environment:
#  &x-environment
#  ALLOWED_HOSTS: |-
#    pyorc.docker.test
#x-build-args: &x-build-args
# # USER_ID: 1001  # Set if your dev user  is non-1000
# # GROUP_ID: 1001 # Set if your dev group is non-1000
#services:
#  backend:
#    environment:
#      <<: *x-environment
#      SSH_AUTH_SOCK: /ssh-agent
#    volumes:
#      - $SSH_AUTH_SOCK:/ssh-agent
#      - media:/opt/media  # If you want to save media files in a volume
#    build:
#      args:
#        <<: *x-build-args
#  frontend:
#    networks:
#      - default
#      - pontsun
#    labels:
#      - 'traefik.enable=true'
#      - 'traefik.docker.network=pontsun'
#      - 'traefik.backend=pyorc'
#      - 'traefik.port=3000'
#      - 'traefik.frontend.rule=Host:pyorc.docker.test'
#    environment:
#      <<: *x-environment
#    build:
#      args:
#        <<: *x-build-args
#  mailhog:
#    networks:
#      - default
#      - pontsun
#    labels:
#      - 'traefik.enable=true'
#      - 'traefik.docker.network=pontsun'
#      - 'traefik.backend=pyorc_mail'
#      - 'traefik.port=8025'
#      - 'traefik.frontend.rule=Host:pyorc-mail.docker.test'
#networks:
#  pontsun:
#    external: true
#volumes:
#  media:
