# Generated by Django 4.0.5 on 2022-07-21 19:47

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pyorc.parties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom affiché')),
                ('codename', models.CharField(max_length=100, verbose_name='Nom unique')),
                ('is_table_number_required', models.BooleanField(verbose_name='Requiert un numéro de table')),
                ('is_availability_required', models.BooleanField(verbose_name='Requiert une vérification de disponibilité')),
                ('order', models.SmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date de création')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la partie')),
                ('scenario_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du scénario')),
                ('is_desk_registration', models.BooleanField(default=False, verbose_name='Inscription au stand')),
                ('desk_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du stand')),
                ('min_players', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Nombre minimum de participant·exs')),
                ('max_players', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Nombre maximum de participant·exs')),
                ('table_amount', models.PositiveIntegerField(default=1, verbose_name='Nombre de table(s) requise(s)')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
                ('note_to_organizers', models.TextField(blank=True, verbose_name='Note aux organisateur·icexs')),
                ('year', models.PositiveIntegerField(default=pyorc.parties.models.current_year, verbose_name='Année de la convention')),
                ('start', models.DateTimeField(verbose_name='Date et heure de début')),
                ('duration', models.PositiveIntegerField(verbose_name='Durée en minutes')),
                ('status', models.SmallIntegerField(choices=[(0, 'en attente de validation'), (1, 'validée'), (2, 'refusée'), (3, 'annulée')], verbose_name='Status actuel')),
                ('party_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parties.partytype', verbose_name='Type de partie')),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ['-year', '-start', '-created_at'],
            },
        ),
    ]
